#### Applying ANN on 50_startups dataset

In [1]:
# 1. Importing the Libraries
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("50_Startups.csv")


In [3]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
dataset.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       49.000000        49.000000      50.000000
mean    73721.615600   121564.038163    212725.266735  112012.639200
std     45902.256482    28264.721000    122959.103760   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103057.490000    134050.070000   90138.902500
50%     73051.080000   122782.750000    214634.810000  107978.190000
75%    101602.800000   145077.580000    299737.290000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   49 non-null     float64
 2   Marketing Spend  49 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [6]:
# Checking for null values
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [7]:
dataset.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    1
State              0
Profit             0
dtype: int64

In [8]:
dataset["Administration"].mean()


121564.03816326526

In [9]:
dataset["Marketing Spend"].mean()

212725.26673469393

In [10]:
dataset["Administration"].fillna(dataset["Administration"].mean(), inplace=True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(), inplace=True)

In [11]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [12]:
# Splitting the data into X and Y
x = dataset.iloc[:,:4].values
y = dataset.iloc[:,4:5].values

In [13]:
type(x)

numpy.ndarray

In [14]:
type(y)

numpy.ndarray

In [15]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 212725.26673469393, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 121564.03816326526, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16

In [16]:
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

In [17]:
dataset["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [18]:
x.shape

(50, 4)

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [20]:
ct=ColumnTransformer([("one", OneHotEncoder(), [3])], remainder="passthrough")
x=ct.fit_transform(x)

In [21]:
x.shape

(50, 6)

In [22]:
x[0]

array([0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1], dtype=object)

In [23]:
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 212725.26673469393],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 121564.03816326526, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 9

In [25]:
dataset.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80    471784.100000    New York  192261.83
1  162597.70       151377.59    443898.530000  California  191792.06
2  153441.51       101145.55    407934.540000     Florida  191050.39
3  144372.41       118671.85    383199.620000    New York  182901.99
4  142107.34        91391.77    366168.420000     Florida  166187.94
5  131876.90        99814.71    362861.360000    New York  156991.12
6  134615.46       147198.87    212725.266735  California  156122.51
7  130298.13       145530.06    323876.680000     Florida  155752.60
8  120542.52       148718.95    311613.290000    New York  152211.77
9  123334.88       108679.17    304981.620000  California  149759.96

In [26]:
y.shape

(50, 1)

In [27]:
# Splitting the data into train and test
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [30]:
print(x.shape," - xshape")
print(y.shape," - yshape")
print(x_train.shape," - x_train shape")
print(x_test.shape," - x_test shape")
print(y_train.shape," - y_train shape")
print(y_test.shape," - y_test shape")

(50, 6)  - xshape
(50, 1)  - yshape
(40, 6)  - x_train shape
(10, 6)  - x_test shape
(40, 1)  - y_train shape
(10, 1)  - y_test shape


In [31]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [32]:
# Model Building
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense

In [33]:
# modelname = Sequential()
regression = Sequential()

In [34]:
#Adding input, hidden and output layers
regression.add(Dense( units=6 , kernel_initializer= "random_uniform", activation="relu"))
regression.add(Dense( units= 12, kernel_initializer= "random_uniform", activation="relu"))
regression.add(Dense( units= 1, kernel_initializer= "random_uniform", activation="relu"))

In [35]:
regression.compile(optimizer = "adam", loss = "mse", metrics=['mse'])

In [36]:
regression.fit(x_train,y_train, epochs=10000)

Streaming output truncated to the last 5000 lines.
2/2 [==============================] - 0s 5ms/step - loss: 246076896.0000 - mse: 246076896.0000
Epoch 7502/10000
2/2 [==============================] - 0s 4ms/step - loss: 245910272.0000 - mse: 245910272.0000
Epoch 7503/10000
2/2 [==============================] - 0s 6ms/step - loss: 245721344.0000 - mse: 245721344.0000
Epoch 7504/10000
2/2 [==============================] - 0s 4ms/step - loss: 245544528.0000 - mse: 245544528.0000
Epoch 7505/10000
2/2 [==============================] - 0s 5ms/step - loss: 245345120.0000 - mse: 245345120.0000
Epoch 7506/10000
2/2 [==============================] - 0s 5ms/step - loss: 245157984.0000 - mse: 245157984.0000
Epoch 7507/10000
2/2 [==============================] - 0s 5ms/step - loss: 244993072.0000 - mse: 244993072.0000
Epoch 7508/10000
2/2 [==============================] - 0s 5ms/step - loss: 244790576.0000 - mse: 244790576.0000
Epoch 7509/10000
2/2 [==============================] - 0s 5ms

In [37]:
ypred = regression.predict(x_test)

In [38]:
ypred 

array([[101159.55],
       [127547.87],
       [128183.22],
       [ 79659.85],
       [173505.66],
       [112934.18],
       [ 69979.64],
       [ 97207.8 ],
       [113349.06],
       [162568.66]], dtype=float32)

In [39]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [40]:
ypred=ypred>0

In [41]:
ypred

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [42]:
dataset.head(1)

R&D Spend  Administration  Marketing Spend     State     Profit
0   165349.2        136897.8         471784.1  New York  192261.83

In [43]:
dataset.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80    471784.100000    New York  192261.83
1  162597.70       151377.59    443898.530000  California  191792.06
2  153441.51       101145.55    407934.540000     Florida  191050.39
3  144372.41       118671.85    383199.620000    New York  182901.99
4  142107.34        91391.77    366168.420000     Florida  166187.94
5  131876.90        99814.71    362861.360000    New York  156991.12
6  134615.46       147198.87    212725.266735  California  156122.51
7  130298.13       145530.06    323876.680000     Florida  155752.60
8  120542.52       148718.95    311613.290000    New York  152211.77
9  123334.88       108679.17    304981.620000  California  149759.96

In [44]:
yp = regression.predict(sc.transform(ct.transform([[165349.20, 136897.80, 471784.100000, "New York"]])))

In [45]:
yp

array([[198667.39]], dtype=float32)

In [46]:
yp = regression.predict(sc.transform(ct.transform([[123334.88, 108679.17, 304981.620000, "California"]])))

In [47]:
yp

array([[150698.67]], dtype=float32)

In [48]:
yp = regression.predict(sc.transform(ct.transform([[130298.13, 145530.06, 323876.680000, "Florida"]])))

In [49]:
yp

array([[154952.45]], dtype=float32)